numero = int(input("Digite um número de 1 a 10: "))

print("\nTabuada de Multiplicação:")
print(f"{numero} x 1 = {numero * 1}")
print(f"{numero} x 2 = {numero * 2}")
print(f"{numero} x 3 = {numero * 3}")
print(f"{numero} x 4 = {numero * 4}")
print(f"{numero} x 5 = {numero * 5}")
print(f"{numero} x 6 = {numero * 6}")
print(f"{numero} x 7 = {numero * 7}")
print(f"{numero} x 8 = {numero * 8}")
print(f"{numero} x 9 = {numero * 9}")
print(f"{numero} x 10 = {numero * 10}")

print("\nTabuada de Divisão:")
print(f"{numero} ÷ 1 = {numero / 1}")
print(f"{numero} ÷ 2 = {numero / 2}")
print(f"{numero} ÷ 3 = {numero / 3}")
print(f"{numero} ÷ 4 = {numero / 4}")
print(f"{numero} ÷ 5 = {numero / 5}")
print(f"{numero} ÷ 6 = {numero / 6}")
print(f"{numero} ÷ 7 = {numero / 7}")
print(f"{numero} ÷ 8 = {numero / 8}")
print(f"{numero} ÷ 9 = {numero / 9}")
print(f"{numero} ÷ 10 = {numero / 10}")

print("\nTabuada de Subtração:")
print(f"{numero} - 1 = {numero - 1}")
print(f"{numero} - 2 = {numero - 2}")
print(f"{numero} - 3 = {numero - 3}")
print(f"{numero} - 4 = {numero - 4}")
print(f"{numero} - 5 = {numero - 5}")
print(f"{numero} - 6 = {numero - 6}")
print(f"{numero} - 7 = {numero - 7}")
print(f"{numero} - 8 = {numero - 8}")
print(f"{numero} - 9 = {numero - 9}")
print(f"{numero} - 10 = {numero - 10}")

print("\nTabuada de Adição:")
print(f"{numero} + 1 = {numero + 1}")
print(f"{numero} + 2 = {numero + 2}")
print(f"{numero} + 3 = {numero + 3}")
print(f"{numero} + 4 = {numero + 4}")
print(f"{numero} + 5 = {numero + 5}")
print(f"{numero} + 6 = {numero + 6}")
print(f"{numero} + 7 = {numero + 7}")
print(f"{numero} + 8 = {numero + 8}")
print(f"{numero} + 9 = {numero + 9}")
print(f"{numero} + 10 = {numero + 10}")



